version: '3.8'

services:
  discord-clone:
    build: .
    ports:
      - "8080:8080"     # HTTP port
      - "8081:8081/udp" # UDP port for P2P
    volumes:
      - discord_data:/data
    environment:
      - HTTP_PORT=8080
      - UDP_PORT=8081
      - DB_PATH=/data/discord.db
    restart: unless-stopped
    
  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - discord-clone
    restart: unless-stopped

volumes:
  discord_data:

